### ISSUE TITLE
Unknown packager

### ISSUE THREAD

**Issue by cavebring** [juks/SocketQueue#36]
Hello,
I cloned a fresh copy and tested with your curl example but only get this error. 

Anyone experienced this or have a clue why it behaves this way?

```
[ec2-user@ SocketQueue]$ node socketQueue.js --upstreamHost=localhost --upstreamPort=5555 --listenPort=2014 --vv --echoServerPort=5555 --testRealLife
2019-04-28 21:23:08 - info: Important: starting...                         
2019-04-28 21:23:08 - info: Remote host configuration name: smartVista                         
2019-04-28 21:23:08 - info: Connecting to upstream server localhost:5555                         
2019-04-28 21:23:08 - info: Relay raw ISO-8583 server is now running on port 2014                         
2019-04-28 21:23:08 - info: Echo server is now running on port 5555
                         
2019-04-28 21:23:08 - info: Connected to upstream 127.0.0.1:5555!                         
2019-04-28 21:23:08 - info: Processing queue [pending 0 / total 0]                         
2019-04-28 21:23:08 - info: The queue is empty                         
2019-04-28 21:23:12 - info: Client ::ffff:61657 connected                         
2019-04-28 21:23:12 - info: Client ::ffff:61657 sent data (830b)                         
2019-04-28 21:23:12 - verbose: [POST...H...]                         
Error unpacking data from bit 16
Packager: undefined: Unknown packager 16 Error: Unknown packager 16
    at _unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:24:28)
    at unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:86:23)
    at new Iso8583Packet (/home/ec2-user/SocketQueue/lib/iso8583-packet/lib/iso8583Packet.js:47:37)
    at queue.addMessage (/home/ec2-user/SocketQueue/lib/iso8583-queue/lib/iso8583Queue.js:50:11)
    at Upstream.sendData (/home/ec2-user/SocketQueue/lib/socketServer/lib/upstream.js:77:24)
    at Socket.<anonymous> (/home/ec2-user/SocketQueue/lib/socketServer/lib/clientSocket.js:47:21)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
Error unpacking data from bit 19
Packager: undefined: Unknown packager 19 Error: Unknown packager 19
    at _unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:24:28)
    at unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:86:23)
    at new Iso8583Packet (/home/ec2-user/SocketQueue/lib/iso8583-packet/lib/iso8583Packet.js:47:37)
    at queue.addMessage (/home/ec2-user/SocketQueue/lib/iso8583-queue/lib/iso8583Queue.js:50:11)
    at Upstream.sendData (/home/ec2-user/SocketQueue/lib/socketServer/lib/upstream.js:77:24)
    at Socket.<anonymous> (/home/ec2-user/SocketQueue/lib/socketServer/lib/clientSocket.js:47:21)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
Error unpacking data from bit 26
Packager: undefined: Unknown packager 26 Error: Unknown packager 26
    at _unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:24:28)
    at unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:86:23)
    at new Iso8583Packet (/home/ec2-user/SocketQueue/lib/iso8583-packet/lib/iso8583Packet.js:47:37)
    at queue.addMessage (/home/ec2-user/SocketQueue/lib/iso8583-queue/lib/iso8583Queue.js:50:11)
    at Upstream.sendData (/home/ec2-user/SocketQueue/lib/socketServer/lib/upstream.js:77:24)
    at Socket.<anonymous> (/home/ec2-user/SocketQueue/lib/socketServer/lib/clientSocket.js:47:21)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
Error unpacking data from bit 29
Packager: undefined: Unknown packager 29 Error: Unknown packager 29
    at _unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:24:28)
    at unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:86:23)
    at new Iso8583Packet (/home/ec2-user/SocketQueue/lib/iso8583-packet/lib/iso8583Packet.js:47:37)
    at queue.addMessage (/home/ec2-user/SocketQueue/lib/iso8583-queue/lib/iso8583Queue.js:50:11)
    at Upstream.sendData (/home/ec2-user/SocketQueue/lib/socketServer/lib/upstream.js:77:24)
    at Socket.<anonymous> (/home/ec2-user/SocketQueue/lib/socketServer/lib/clientSocket.js:47:21)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
Error unpacking data from bit 34
Packager: undefined: Unknown packager 34 Error: Unknown packager 34
    at _unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:24:28)
    at unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:86:23)
    at new Iso8583Packet (/home/ec2-user/SocketQueue/lib/iso8583-packet/lib/iso8583Packet.js:47:37)
    at queue.addMessage (/home/ec2-user/SocketQueue/lib/iso8583-queue/lib/iso8583Queue.js:50:11)
    at Upstream.sendData (/home/ec2-user/SocketQueue/lib/socketServer/lib/upstream.js:77:24)
    at Socket.<anonymous> (/home/ec2-user/SocketQueue/lib/socketServer/lib/clientSocket.js:47:21)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
Error unpacking data from bit 36
Packager: undefined: Unknown packager 36 Error: Unknown packager 36
    at _unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:24:28)
    at unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:86:23)
    at new Iso8583Packet (/home/ec2-user/SocketQueue/lib/iso8583-packet/lib/iso8583Packet.js:47:37)
    at queue.addMessage (/home/ec2-user/SocketQueue/lib/iso8583-queue/lib/iso8583Queue.js:50:11)
    at Upstream.sendData (/home/ec2-user/SocketQueue/lib/socketServer/lib/upstream.js:77:24)
    at Socket.<anonymous> (/home/ec2-user/SocketQueue/lib/socketServer/lib/clientSocket.js:47:21)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
Error unpacking data from bit 44
Packager: undefined: Unknown packager 44 Error: Unknown packager 44
    at _unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:24:28)
    at unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:86:23)
    at new Iso8583Packet (/home/ec2-user/SocketQueue/lib/iso8583-packet/lib/iso8583Packet.js:47:37)
    at queue.addMessage (/home/ec2-user/SocketQueue/lib/iso8583-queue/lib/iso8583Queue.js:50:11)
    at Upstream.sendData (/home/ec2-user/SocketQueue/lib/socketServer/lib/upstream.js:77:24)
    at Socket.<anonymous> (/home/ec2-user/SocketQueue/lib/socketServer/lib/clientSocket.js:47:21)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
Error unpacking data from bit 50
Packager: undefined: Unknown packager 50 Error: Unknown packager 50
    at _unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:24:28)
    at unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:86:23)
    at new Iso8583Packet (/home/ec2-user/SocketQueue/lib/iso8583-packet/lib/iso8583Packet.js:47:37)
    at queue.addMessage (/home/ec2-user/SocketQueue/lib/iso8583-queue/lib/iso8583Queue.js:50:11)
    at Upstream.sendData (/home/ec2-user/SocketQueue/lib/socketServer/lib/upstream.js:77:24)
    at Socket.<anonymous> (/home/ec2-user/SocketQueue/lib/socketServer/lib/clientSocket.js:47:21)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
Error unpacking data from bit 59
Packager: undefined: Unknown packager 59 Error: Unknown packager 59
    at _unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:24:28)
    at unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:86:23)
    at new Iso8583Packet (/home/ec2-user/SocketQueue/lib/iso8583-packet/lib/iso8583Packet.js:47:37)
    at queue.addMessage (/home/ec2-user/SocketQueue/lib/iso8583-queue/lib/iso8583Queue.js:50:11)
    at Upstream.sendData (/home/ec2-user/SocketQueue/lib/socketServer/lib/upstream.js:77:24)
    at Socket.<anonymous> (/home/ec2-user/SocketQueue/lib/socketServer/lib/clientSocket.js:47:21)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
Error unpacking data from bit 61
Packager: undefined: Unknown packager 61 Error: Unknown packager 61
    at _unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:24:28)
    at unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:86:23)
    at new Iso8583Packet (/home/ec2-user/SocketQueue/lib/iso8583-packet/lib/iso8583Packet.js:47:37)
    at queue.addMessage (/home/ec2-user/SocketQueue/lib/iso8583-queue/lib/iso8583Queue.js:50:11)
    at Upstream.sendData (/home/ec2-user/SocketQueue/lib/socketServer/lib/upstream.js:77:24)
    at Socket.<anonymous> (/home/ec2-user/SocketQueue/lib/socketServer/lib/clientSocket.js:47:21)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
Error unpacking data from bit 63
Packager: undefined: Unknown packager 63 Error: Unknown packager 63
    at _unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:24:28)
    at unpack (/home/ec2-user/SocketQueue/lib/iso8583/lib/iso8583.js:86:23)
    at new Iso8583Packet (/home/ec2-user/SocketQueue/lib/iso8583-packet/lib/iso8583Packet.js:47:37)
    at queue.addMessage (/home/ec2-user/SocketQueue/lib/iso8583-queue/lib/iso8583Queue.js:50:11)
    at Upstream.sendData (/home/ec2-user/SocketQueue/lib/socketServer/lib/upstream.js:77:24)
    at Socket.<anonymous> (/home/ec2-user/SocketQueue/lib/socketServer/lib/clientSocket.js:47:21)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
2019-04-28 21:23:12 - info: ::ffff:61657: Warning! Failed to parse iso8583 packet. Won't queue!                         
2019-04-28 21:23:12 - info: Client ::ffff:61657 <end> event                         
2019-04-28 21:23:12 - info: Client ::ffff:61657 <close> event 
```

**Comment by juks** [comment]
Hi!

Looks like you curl to binary port. You need to run the server with --listenHttpPort=PORT option, then curl to this PORT.
